### ISSUE TITLE
Data classes in another module 

### ISSUE THREAD

**Issue by Sam-Kruglov** [Pozo/mapstruct-kotlin#4] opened 2020-01-11 11:37 UTC
Hi, thanks a lot for this project!

I have a maven module with data classes all annotated with `@KotlinBuilder` and all the builders are successfully created and put into the jar.
I have another maven module that depends on the data classes and it tries to use mapstruct mapping these data classes to something.

During compilation kapt throws an error that "no parameterless constructor exists for type", basically, it doesn't see the builders but it does see the class itself. Not sure why is that, because they are both laying in the same folder in that jar. 

May or may not be related to https://github.com/rzwitserloot/lombok/issues/1538

**Comment by Sam-Kruglov** [comment] 2020-01-11 11:44
![Screenshot 2020-01-11 at 13 42 33](https://user-images.githubusercontent.com/23556336/72203744-45ccf000-3478-11ea-97a3-bb4bc4c8a22d.png)

There's a link to the project but I constantly force push it, so probably won't be that useful. Hopefully, you get the idea :) https://github.com/Sam-Kruglov/bank/blob/under_construction

**Comment by Pozo** [comment] 2020-01-11 11:50
Hello @Sam-Kruglov thank you for your report. I'm getting 404 for your link. Could you create a very simple project and share with me where you can reproduce this issue?

**Comment by Sam-Kruglov** [comment] 2020-01-11 11:51
Not sure where did the `blob` came from, here is the correct link https://github.com/Sam-Kruglov/bank/tree/under_construction.

I will create a special branch in a second

**Comment by Sam-Kruglov** [comment] 2020-01-11 11:53
I will create a test branch in a second

**Comment by Pozo** [comment] 2020-01-11 12:24
Thanks now I could check it. I can see the generated builder classes too, however I think this problem is out of this library's focus. I suggest you to minimize the maven project structure, the current one is too complicated.

**Comment by Sam-Kruglov** [comment] 2020-01-11 13:49
Should I create this issue for the root mapstruct project?

**Comment by Sam-Kruglov** [comment] 2020-01-11 14:05
I rewrote data classes module into java + lombok module, now it all works

**Comment by Sam-Kruglov** [comment] 2020-01-11 15:29
But that shows that the problem is most likely in this library though since the same setup works with another builder library

**Comment by Pozo** [comment] 2020-01-13 09:40
@Sam-Kruglov Understood, I'll check it :+1:

**Comment by m-kay** [comment] 2020-01-14 13:40
I think the problem is `@Retention(AnnotationRetention.SOURCE)` of the `@KotlinBuilder` annotation since this is checked in the `KotlinBuilderProvider` but not available anymore. I'm having the same problem when I want to use the data classes in another project included via maven dependency.

**Closed as completed** 2020-01-19 18:01 UTC
Labels: bug

**Comment by Pozo** [comment] 2020-01-19 18:04
@Sam-Kruglov Finally I could check @m-kay s suggestion and it seems to work fine now. @m-kay thank you again your contribution, I'm going to release it soon. The version number will be `1.3.1.1`

**Comment by Pozo** [comment] 2020-01-19 21:34
@Sam-Kruglov @m-kay Now it's available from the central repository.

**Comment by Sam-Kruglov** [comment] 2020-01-21 15:44
Thank you, worked nicely :)
